### ISSUE TITLE
[HELP WANTED]: src.aihawk_job_manager:start_applying:158 - Error during job application: descriptor 'lower' for 'str' objects doesn't apply to a 'NoneType' object

### ISSUE THREAD

**Issue by surajmoolya** [AIHawk-co/Auto_Jobs_Applier#634]
### Issue description

Getting this error for every job applications
![image](https://github.com/user-attachments/assets/ac556c69-a72c-4f90-9231-a29a5fd729c5)

**Comment by FrancescoVassalli** [comment]
I think something in your configuration.yaml is formatted incorrectly

**Comment by lukalafaye** [comment]
Having the same issue here. My yaml has no syntax error.

```yaml

remote: false

experienceLevel:
  entry: true
  internship: false
  associate: false
  mid-senior level: false
  director: false
  executive: false

jobTypes:
  full-time: false
  contract: true
  part-time: false
  temporary: false
  internship: true
  other: false
  volunteer: false

date:
  all time: true
  month: false
  week: false
  24 hours: false

positions:
#  - Ingénieur IA
#  - Ingénieur Intelligence Artificielle
#  - Ingénieur Machine Learning
  - Artificial Intelligence
#  - Machine Learning Engineer
#  - AI Research Scientist
#  - ML Research Scientist
#  - Machine Learning Research Scientist

locations:
  - United States
  - United Kingdom
  - Australia
  - Switzerland
#  - France

apply_once_at_company: true

distance: 50

company_blacklist:
  - Random

title_blacklist:
  - Finance
  - Marketing
  - Advertising
  - Banks
  - Sales
  - Bank
  - Physics
  - Web
  - Chemistry
  - Design
  - Business
  - Freelance
  - Automation

location_blacklist:
  - Brazil

job_applicants_threshold:
  min_applicants: 0
  max_applicants: 9999

llm_model_type: openai
llm_model: 'gpt-4o-mini'
# llm_api_url: 'https://api.pawan.krd/cosmosrp/v1'
```
