### ISSUE TITLE
[BUG]: It doesn't exclude senior positions even though only entry and associate in experienceLevel have been specified

### ISSUE THREAD

**Issue by Axedyson** [AIHawk-co/Auto_Jobs_Applier#636]
### Describe the bug

The program still applies to senior positions even though the only fields in the `experienceLevel` scope in the `config.yaml` file that has been set to `true` are `entry` and `associate`.

### Steps to reproduce

Just run the program with the following settings in the `experienceLevel` field in the `config.yaml` file:

```yaml
experienceLevel:
  internship: false
  entry: true
  associate: true
  mid-senior level: false
  director: false
  executive: false
  ```

### Expected behavior

That the program excludes senior positions

### Actual behavior

It still applied to senior positions

### Branch

main

### Python version

Python 3.12.7 (64b)

### LLM Used

OpenAI's ChatGPT

### Model used

gtp-4o
